### ISSUE TITLE
Fee Recipient Post Merge (WIP)

### ISSUE THREAD

**Issue by james-prysm** [ethereum/keymanager-APIs#23]
Post Merge, consensus clients will need to set an Eth 1 account when running a validator/beacon Chain in order to receive the fees on processing transactions while proposing a block. Currently, PoS validators only receive funds from the protocol and do not receive fees on the transactions themselves. Users would like a way to tell the Validator Client/ Beacon Node to change the fee recipients dynamically while the system is running. 

Each validator index ( not public key according to this api https://github.com/ethereum/beacon-APIs/pull/178) can have a fee recipient.

**Comment by james-prysm** [comment]
How do we protect this endpoint 🤔  ? is it merged into the existing endpoints or separate?

**Comment by dapplion** [comment]
To clarify this would be added to a validator_client oapi file not the keymanager right? Drawing similarities, the keymanager API does not handle graffiti.

**Comment by james-prysm** [comment]
first spec used for fee recipient api merged in, closing issue.
