### ISSUE TITLE
Contradiction in the `DELETE feerecipient` documentation.

### ISSUE THREAD

**Issue by zah** [ethereum/keymanager-APIs#35]
The documentation of the `DELETE /eth​/v1​/validator​/{pubkey}​/feerecipient` call currently states that status code 204 should be returned to indicate that "Successfully removed the mapping, or there was no mapping to remove for a key that the server is managing."

This contradicts the error codes section which states that status code 404 is returned when "The key was not found on the server, nothing to delete."

There is also an inconsistency between the success status code of this call and the other DELETE calls which return status 200 upon success.

**Comment by Alkhtri77** [comment]
Ok

**Comment by rolfyone** [comment]
this sounds stale - closing.
