### ISSUE TITLE
Alpha release request

### ISSUE THREAD

**Issue by g11tech** [ethereum/keymanager-APIs#51]
Would it be possible to have an alpha release of the api spec, as the release would build a oapi json specification, that for e.g. can be easily consumed by for e.g. CI spec tester of lodestar.

Something like this: https://github.com/ethereum/beacon-APIs/releases/download/v2.3.0/beacon-node-oapi.json

**Comment by wemeetagain** [comment]
cc @dapplion

**Comment by dapplion** [comment]
> cc @dapplion

Sounds good to me, someone has to prepare the github workflows machinery. Just copy from beacon-APIs

**Comment by james-prysm** [comment]
will take a look at this next week...
