### ISSUE TITLE
v1.0.0 site is down

### ISSUE THREAD

**Issue by michaelsproul** [ethereum/keymanager-APIs#62]
I'm not sure why, but the v1.0.0 site is erroring at the moment: https://ethereum.github.io/keymanager-APIs/

![error](https://github.com/ethereum/keymanager-APIs/assets/4452260/a4c19d31-0387-4f39-9545-16bda91534ae)

The first error in the console seems to be:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.allorigins.win/raw?url=https://github.com/ethereum/keymanager-APIs/releases/download/v1.0.0/keymanager-oapi.yaml. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 521.

**Comment by michaelsproul** [comment]
Changing to `dev` works

**Comment by michaelsproul** [comment]
seems to be back now, idk what happened. Might have been a server outage on whatever `allorigins.win` is

**Comment by rolfyone** [comment]
ok, lets assume it's ok and close this for now.
